name: Publish Docker image

on:
  push: {}

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Publish Docker image
        uses: Luzifer/actions/docker-publish@032da29d4fb988e8209bed077a1c3d834468431a # develop
        with:
          image_name: ghcr.io/luzifer/kopia-healthcheck
          registry_pass: ${{ secrets.GITHUB_TOKEN }}
          registry_user: ${{ github.actor }}
