name: Publish Docker image

on:
  push: {}

permissions:
  contents: read
  packages: write

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Publish Docker image
        uses: Luzifer/actions/docker-publish@fe674b660989d3a32e54f50355fbf9e3b31f5d0e # develop
        with:
          image_name: ghcr.io/luzifer/kopia-healthcheck
          registry_pass: ${{ secrets.GITHUB_TOKEN }}
          registry_user: ${{ github.actor }}
